version: '2'
services:
  cassandra:
    image: public.ecr.aws/bitnami/cassandra:4.1.3
    ports:
      - 9042:9042
    volumes:
      - ~/apps/cassandra:/var/lib/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=cloudinfra
